# Generated by Django 3.2.8 on 2021-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
