# Generated by Django 3.2.8 on 2022-01-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_list_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='archive',
            new_name='archived',
        ),
        migrations.AddField(
            model_name='card',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.board'),
        ),
    ]
