# Generated by Django 3.2.8 on 2022-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
