# Generated by Django 3.2.8 on 2022-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_board_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('workspace', 'Workspace')], default='workspace', max_length=64),
        ),
    ]
