FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /backend

RUN apt-get update && apt-get install ffmpeg -y

COPY ./requirements.txt /backend/

RUN pip install -r requirements.txt

