FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /backend

RUN apt-get update && apt-get install gunicorn ffmpeg -y

COPY ./requirements.txt /backend/

RUN --mount=type=cache,target=/root/.cache/pip pip install --default-timeout=2000 -r requirements.txt

