name: Aidudu CI/CD
on:
  push:
    branches:
      - release
jobs:
  github_actions_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - run: docker system prune --volumes -f
      - run: docker-compose -f docker-compose.prod.yml down
      - run: docker-compose -f docker-compose.prod.yml build
      - run: docker-compose -f docker-compose.prod.yml up -d
      - run: docker exec aidudu_backend_1 python manage.py test api.tests.unit_tests