name: Aidudu CI/CD
on:
  push:
    branches:
      - devops
      - develop
jobs:
  github_actions_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.prod.yml down
      - run: docker-compose -f docker-compose.prod.yml up -d