name: Aidudu CI/CD
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
jobs:
  aidudu_ci_cd:
    runs-on: self-hosted
    steps:
      - run: echo ${{secrets.PASSWD}} | sudo -S chown -R $USER:$USER /home/administrator/actions-runner/_work/aidudu
      - uses: actions/checkout@v2
      # - run: docker system prune --volumes -f
      - run: docker-compose -f docker-compose.prod.yml down
      - run: docker-compose -f docker-compose.prod.yml up --build -d
      - run: docker exec aidudu_backend_1 python manage.py test api.tests.unit_tests